### ISSUE TITLE
Error while creating a highlighting while selecting a single line with visual line mode

### ISSUE THREAD

**Issue by david-pikas** [azabiong/vim-highlighter#15]
See title.

Selecting a single line in visual line mode and then pressing `f<CR>` causes the following error:

```
Error detected while processing function highlighter#Command[22]..<SNR>168_SetHighlight[28]..<SNR>168_GetVisualLine:
line    9:
E951: \% value too large
```

After the error is dismissed the line is successfully highlighted

Digging around, the error seems to occur at line 264 of `autoload/highlighter.vim`. One guess is that it is caused by an of-by-one error and indeed changing `l:right` to `l:right-1` does cause the error to go away. I'm not sure what the intended purpose of the function is as the highlighting seems to work even when the error occurs so I'm not sure that this fix preserves the intended functionality of the code.

**Comment by azabiong** [comment]
Thank you for reporting this error 👍 
Now there is an update. Would you please try it?

**Comment by david-pikas** [comment]
The error seems to be fixed now!

**Comment by azabiong** [comment]
Great, Thanks!
