### ISSUE TITLE
Feature Request: add support for line-pattern (\%l)

### ISSUE THREAD

**Issue by JS-Zheng** [azabiong/vim-highlighter#16]
Line patterns are very useful in Vim:
```vim
				*/\%l* */\%>l* */\%<l* *E951* *E1204* *E1273*
\%23l	Matches in a specific line.
```

For example, I can highlight the `Leader` just at 312th line by:
```vim
Hi+ \%312lLeader
```
<img width="472" alt="截圖 2022-11-09 00 48 47" src="https://user-images.githubusercontent.com/16326004/200625681-8f613eda-bca6-43bb-9e60-7dd690d5f7d8.png">
  
or highlight the entire 312th line by:
```vim
Hi+ \%312l
```
  
However, vim-highlighter doesn't support patterns like this very well now (e.g., `Hi-` cmd)
I think this feature is very useful!

**Comment by azabiong** [comment]
That's good idea! 👍 
I will think about how to do that, thanks!

**Comment by azabiong** [comment]
Now it supports that 😄 
Currently, only the function to erase the exact same pattern set by the "Hi+" command is supported. And I think that the function can be gradually expanded in the future.

**Comment by azabiong** [comment]
Now it also supports `HiErase` key function. I hope you like it! 😄

**Comment by azabiong** [comment]
Hi Jason, now `HiSetSL`  key mapping also supports highlighting in a specific line, and it looks convenient! 😄 
 →&nbsp; [Highlights in a specific line](https://github.com/azabiong/vim-highlighter#highlights-in-a-specific-line)
