### ISSUE TITLE
Getting No such group or event error

### ISSUE THREAD

**Issue by dcDeba** [azabiong/vim-highlighter#17]
I am getting the below error when I try to open any file:

Error detected while processing  ~/.vim/pack/azabiong/start/vim-highlighter/plugin/highlighter.vim:
line   58:
E216: No such group or event: ColorSchemePre * call highlighter#ColorScheme('pre')

Note: I am using **gruvbox** as my colorscheme

**Comment by azabiong** [comment]
Thanks for your interest in this plugin.
I guess upgrading to a newer version of Vim or Neovim seems like a simple solution.

**Comment by dcDeba** [comment]
Seems like upgrading my vim from 8.0 to 8.2 resolved the issue. Thank you !!
