### ISSUE TITLE
Unable to save when whitespaces in the path

### ISSUE THREAD

**Issue by sevehub** [azabiong/vim-highlighter#18]
I noticed that :HI save doesn't support filenames with whitespaces in the path, at least on Windows OS.
E.g. :Hi save "filename with empty spaces.hl"

I have tried to place the filename inside single quote, double quote, and escape space characters, but it didn't fix the issue.

**Comment by azabiong** [comment]
Thanks for reporting this issue and various tests. Now there is an update to support this. Would you like to try it?

**Comment by sevehub** [comment]
Awesome, it looks good. Thanks.
