### ISSUE TITLE
No such group or event: ColorSchemePre * call highlighter#ColorScheme('pre') after installing

### ISSUE THREAD

**Issue by Viser** [azabiong/vim-highlighter#2]
Hi, I've got such error just after install

Error detected while processing /home/user/.vim/bundle/vim-highlighter/plugin/highlighter.vim:
line   47:
E216: No such group or event: ColorSchemePre * call highlighter#ColorScheme('pre')

Can you please advise?

**Comment by azabiong** [comment]
Hi Mitya,
Thank you for checking this.
May I know your vim version?
Thanks

**Comment by Viser** [comment]
NVIM v0.5.1

**Comment by azabiong** [comment]
I guess the event ColorSchemePre should be supported in the version already, but why it tells that it is not defined? 
If possible, I think it would be a good idea to re-install recent version of nvim.

**Comment by Viser** [comment]
hmmm, got it working after plugin reinstall

**Comment by azabiong** [comment]
Great! thank you for the update.

**Comment by Viser** [comment]
Thanks for support!
