### ISSUE TITLE
Can we expose HiSet, HiErase etc as vim commands?

### ISSUE THREAD

**Issue by SandeepTuniki** [azabiong/vim-highlighter#23]
The documentation specifies the following default maps to trigger the basic highlights:

```
  let HiSet   = 'f<CR>'
  let HiErase = 'f<BS>'
  let HiClear = 'f<C-L>'
  let HiFind  = 'f<Tab>'
```

**Can we instead expose them as vim commands (ex: `:HiSet`)?** This allows us to invoke them in a more programmatic manner. (My use case is that I'm using neovim, and use lua scripting mostly).

**Comment by azabiong** [comment]
Sure, we can also use `Hi` commands. 
To set highlights:
```
:h Hi+
```
To erase highlights:
```
:h Hi-
```

**Comment by SandeepTuniki** [comment]
Sweet! Fits my use-case perfectly. And thanks for the quick response.

**Comment by azabiong** [comment]
Thanks!  And for neovim `lua` configuration, the `basic` > `lua` section of [Configuration Examples](https://github.com/azabiong/vim-highlighter#configuration-examples) might help.
