### ISSUE TITLE
HiSense('N') not working

### ISSUE THREAD

**Issue by mallicksm** [azabiong/vim-highlighter#24]
line 2254 in autoload/highlighter.vim
let l:cmd = (a:key == 'n') ? '>' : '<' 
is not working for me
but when replaced by
   if a:key == 'n' 
       let l:cmd = '>'
    else
       let l:cmd = '<'
    endif
it works, please help

**Comment by mallicksm** [comment]
sorry, here is what works
let l:cmd = (a:key =~# 'n') ? '>' : '<'
because it needs to be case sensitive
please fix

**Comment by azabiong** [comment]
It's great! Thank you for finding the problem and solution together. 👍 
The fix has been updated. Thanks!
