### ISSUE TITLE
HiMapKeys doesnt seem to work

### ISSUE THREAD

**Issue by krzkrzkrz** [azabiong/vim-highlighter#25]
I am using Neovim v9.0.1

I am trying to unset all default keys.

In `~/.config/nvim/lua/core/plugins_config/vim-highlighter.lua`, I have the following:

```
vim.cmd([[
  let HiMapKeys=0
]])
```

Hitting `f` and `<CR>` still triggers the default for `HiSet`. Am I missing something?

**Comment by azabiong** [comment]
Hi, I think that's the correct setting.
Could you try the following code to see if that part of the code is actually called?
```
vim.cmd([[
  let HiMapKeys=0
  echomsg "==Here=="
]])
```
And then we can check it using ` :mes[sage] ` command, after restarting or opening another nvim.

**Comment by azabiong** [comment]
And the desired sequence is to set this variable 'HiMapKeys' somewhere at startup, so that it can be referenced later when the  plugin is actually loaded.

**Comment by krzkrzkrz** [comment]
Typing `:mes`, returns:

```
All parsers are up-to-date!
==Here==
```

> And the desired sequence is to set this variable 'HiMapKeys' somewhere at startup, so that it can be referenced later when the plugin is actually loaded.

Does this mean it should be in the nvim `after` directory?

**Comment by azabiong** [comment]
Looks good!  It means that now we only need to adjust the loading order.
It needs to be set before loading the plugin. So can we try setting it somewhere else before loading the plugin?
And if you prefer Lua, you can also use the following line:
```lua
vim.g.HiMapKeys = 0
```

**Comment by krzkrzkrz** [comment]
Perfect! That works!

**Comment by azabiong** [comment]
Great! &nbsp;I hope you find this tool useful. 😄 Thanks!
