### ISSUE TITLE
How to programmatically set HiSetSL and HiSet (visual mode)

### ISSUE THREAD

**Issue by krzkrzkrz** [azabiong/vim-highlighter#26]
I might have missed reading something in the help file.

But if `vim.keymap.set('n', 'tt', ':Hi+<CR>')` allows me to highlight a set (the equivalent of `HiSet)`

How do I set a keymap for `HiSetSL`? 

Similarly, how do you programmatically set keymaps for `HiSet` and `HiSetSL` in visual select mode?

**Comment by azabiong** [comment]
Oh, you can use ` :Hi+% ` command for `HiSetSL` function.

**Comment by krzkrzkrz** [comment]
Hi, and what about for visual mode?

I was thinking `vim.keymap.set('v', 'tw', ':Hi+x<CR>')` and `vim.keymap.set('v', 'tw', ':Hi+x%<CR>')`? Or am I missing something?

**Comment by azabiong** [comment]
You can use the same key for both normal and visual modes.

So, how about assigning `tt` for both `:Hi+`and `:Hi+x` commands,
and `tw` for `:Hi+%` and `:Hi+x%` ?

**Comment by azabiong** [comment]
I'm glad it's working now.  May I ask a question that in which cases you would prefer direct mapping instead of using predefined variables? Wouldn't it be simpler to assign keys to predefined variables something like ` vim.g.HiSet = 'tt' `

**Comment by krzkrzkrz** [comment]
Ahh, that works better actually. Thank you for pointing that out. Let me close the issue for now
