### ISSUE TITLE
Is there a way to disable the command line abbreviation?

### ISSUE THREAD

**Issue by Asheq** [azabiong/vim-highlighter#27]
I didn't know this `cabbrev` existed but stumbled upon it by surprise. I wanted to search for the text `HI` so I typed `/HI<CR>`, but then all of a sudden it was searching for `Hi` instead, leaving me confused for a bit. I would rather avoid these kinds of surprises, if possible. (It's also weird that `cabbrev` applies to both `:` commands and `/` commands but that is a "problem" with neo/vim itself).

https://github.com/azabiong/vim-highlighter/blob/e625c9a475b760f970c2f813cbe37e9d28cd51ed/plugin/highlighter.vim#L70

Anyway, thanks for the incredible plugin @azabiong!

**Comment by azabiong** [comment]
Thank you for identifying this issue and providing a detailed explanation. 👍 
Now it's fixed!
It was initially introduced for the convenience of command typos. However, since both the `Hi` and `HI` commands are currently supported, I think the `ca` command can be omitted. Thanks!

**Comment by Asheq** [comment]
Great, thanks! 🚀

**Comment by Asheq** [comment]
Closed by 314272f69a4b49b9d06b3e07b44747323f26b9fe
