### ISSUE TITLE
Visual mode highlighting fails

### ISSUE THREAD

**Issue by echo-bravo-yahoo** [azabiong/vim-highlighter#29]
All attempts to highlight text in visual mode fail with `E16: Invalid range`. Other (built-in) vim commands succeed on the same visual selections. I've tried in a variety of types of buffers to confirm it's not an interaction with, e.g., an LSP or highlight setting.

I'm running neovim 0.9.5 with the latest version of vim-highlighter.

**Comment by azabiong** [comment]
Thanks for your update.
Does this happen when you use command line input by pressing the colon `:` in visual mode? For example `:Hi+x`? If so, the auto range prefix `:'<,'>` may be causing this problem. In that case, please try deleting this prefix part and pressing enter. If it works, I would like to recommend using the default key mapping,`HiSet`.

**Comment by echo-bravo-yahoo** [comment]
Hey - that is in fact the issue & solution - thanks!
