### ISSUE TITLE
Error detected while using highlighter.vim

### ISSUE THREAD

**Issue by WritwikRay** [azabiong/vim-highlighter#3]
Hi the following error popped.
I'm using vim 8.1
Not an editor command: const s:FL = s:FindList

**Comment by azabiong** [comment]
Hi, Thanks for the update.
It seems that the 'const' keyword has been introduced at the vim version 8.1.1539. ([vim#4541](https://github.com/vim/vim/pull/4541))
If possible, I would recommend to upgrade vim to the recent version to avoid further problems and to use new features.
I'll update the version compatibility.
