### ISSUE TITLE
[Question] Is it possible to toggle highlight?

### ISSUE THREAD

**Issue by kagbodji** [azabiong/vim-highlighter#30]
Hi there,

I am aware of `Hi +` (f<CR>). and `Hi -` (f<BS>) to add / remove highlight. I am wondering if there exists the functionality to highlight a word/selection if no current highlight exists, else remove the highlight, i.e., toggle the highlight. The idea to use a single keymap to quickly toggle highlight, similar to how [quickhl](https://github.com/t9md/vim-quickhl) does it. If not, I'd like to request this feature. Happy to implement it as well if you can point me in the right direction, I'm a novice in vimscript.

Thanks!

**Comment by azabiong** [comment]
Hi Kwami,
It looks interesting and I think it's a good idea! I added the following options to make it work as you described:
```vim
:h HiSetToggle
```
Would you like to try it? Thank you.

**Comment by kagbodji** [comment]
wow, that was fast!! Works like a charm, thanks!!

**Comment by kagbodji** [comment]
the new `HiSetToggle` setting implements this. Thanks!
