### ISSUE TITLE
[feature request] Command to define colors that are not cleared by `HiClear`

### ISSUE THREAD

**Issue by verboze** [azabiong/vim-highlighter#31]
Hello again,

This request aims to satisfy this use case: there are strings I would like to highlight that I don't want cleared when I issue `HiClear`.  In general, these are things like "debugger", "binding.pry", "console.log", etc -- things that should be removed before committing code to main. While I have CI checks to catch these, it would be great to visually inspect a file and see those things highlighted. Currently, I am using `:14 Hi+ console.log.*` in my vimrc to highlight such lines on load; the problem is when I highlight other things and eventually `HiClear` them when no longer needed, I do lose those highlights as well.

It would be great to have a command like `Hi!` that makes the highlight semi-permanent, so that it is ignored by `HiClear` and can only explicitly be cleared with `Hi -`

Thanks for your consideration!

**Comment by azabiong** [comment]
Hi Kwami,

Thanks for your idea and usage example. For this purpose, the `:Hi load` command seems to be a perfect choice.
Here's how to use it:
1. Open or edit the file containing the keywords you want to highlight.
2. Highlight your keywords in your desired color.
3. Now use the `:Hi save` command to save the highlights to a file. For example:
   ```vim
   :Hi save my_keywords
   ```
4. Then you can reload it anytime using the `:Hi load` command. For example
   ```vim
   :Hi load my_keywords
   ```
If this command is used frequently, you may want to define a keymap or command abbreviation. For example:
   ```vim
   :nn f<C-K> <Cmd>Hi load my_keywords<CR>
   ```

For more info, please see [Save and Load](https://github.com/azabiong/vim-highlighter?tab=readme-ov-file#save--load)

Thanks!

**Comment by verboze** [comment]
Thanks @azabiong, this alternative works for my purposes. Closing this.
