### ISSUE TITLE
HiSearch() not working for one time highlight

### ISSUE THREAD

**Issue by SammysHP** [azabiong/vim-highlighter#34]
When using a one time highlight (`f<BS>`), the `HiSearch()` function does not jump to the next highlight, but calls the native `n` function.

Vim: 9.1-764  
vim-highlighter: 1c106eba93a4c6082007c5762651f114b6b972ff

**Comment by azabiong** [comment]
Thank you for updating this issue. Your description is very clear and concise! 👍 
The new version is ready. Would you like to try it?

**Comment by SammysHP** [comment]
Perfect, 738322317a6b3260ab369116c9dfd11f1d95bb0d fixed the problem, thanks!
