### ISSUE TITLE
[Question] How to navigate highlighters in current buffer?

### ISSUE THREAD

**Issue by jqhr** [azabiong/vim-highlighter#6]
I like this plugin very much! I got some trouble when I browse my code.
For example, I highlight some keyword and I want to find next keyword, I could use <kbd>\*</kbd>, but I don't want change my current search pattern.In addition, some keyword was highlighted by visual select, so <kbd>\*</kbd> was not work.
Just like this:
![图片](https://user-images.githubusercontent.com/23305067/168242807-f5552d52-52db-4854-a46c-eff87b58c299.png)

The cursor was on *imUserNameList*, and I want to goto the next "imUserNameList" position off the screen.
So, how can I do?

**Comment by azabiong** [comment]
I'm glad you liked this tool, and thanks for your comment. I think it could be a useful feature request.
So, as a first step, in this picture, when the cursor is over the world 'imUserNameList', which key would you use to jump to the next matching word?

**Comment by jqhr** [comment]
I'm very happy for your replay.
For me, I  would use <c-n> to move to next position.
Thank you very much.

**Comment by azabiong** [comment]
Now `Hi >` and `Hi <` commands are added to support jumping to the most recently set highlight.
It looks quite close to the goal. In your picture above, after setting visual mode highlight "array[i]",  you can use `Hi >` and `Hi <` commands to jump back and forth to matching "array[i]".  After that, to jump to "imUserNameList", you can either simply set highlight on it, or erase highlight of the current "array[i]" to make "imUserNameList" as the latest one.  Would you like to try it? And, please also check key mapping:
```vim
  :h Hi>
```

**Comment by azabiong** [comment]
I think the next step would be to introduce a command to search for the nearest highlight near the cursor.
For example, ` Hi << `

**Comment by azabiong** [comment]
As a next step I think we can try to jump using the highlighted pattern at the cursor position.
In this case, when we move the cursor from the highlighted word `Before` to `After`, the next jump pattern will be `After`.
What do you think?

**Comment by jqhr** [comment]
I think so.

**Comment by azabiong** [comment]
Thank you, then I'll go ahead and let you know if there is an update.

**Comment by azabiong** [comment]
Hi Jinq, Now `Hi>` command supports jumping to matching highlights at the cursor position, and the new command `Hi}` supports jumping to adjacent highlights. Please see [Jump to Highlight](https://github.com/azabiong/vim-highlighter#jump-to-highlights) section and my key-map recommendation. I hope you like it 😄

**Comment by jqhr** [comment]
I have tried it. Great job! I like it

**Comment by azabiong** [comment]
Very nice! 😄 I added your name to the credits section ` h: Hi-Credits ` for suggesting this useful feature.

**Comment by azabiong** [comment]
Thank you, I added your name to the credits section ` :h  Hi-Credits ` of v1.50.2 for suggesting this useful feature. 😄

**Comment by jqhr** [comment]
Thank you very mutch
