### ISSUE TITLE
[Question] The highlight's color was different from two window.

### ISSUE THREAD

**Issue by jqhr** [azabiong/vim-highlighter#9]
Thanks author very much for solute my problem.
Now I found same pattern of the same buffer was different with two window.
For example
![图片](https://user-images.githubusercontent.com/23305067/170194979-631f2a76-8850-4af8-87f5-dd8af42cfc87.png)
The keyword 'formDataEditor' was highligh in two window. but the color was different.
For Hi/Find formDataEditor multiple files, the color was same, but why Hi/Set word color was different for two window?

Maybe I need some config to keep color same?

**Comment by azabiong** [comment]
Thanks for your update. You can use [Sync Mode](https://github.com/azabiong/vim-highlighter#sync-mode)  and ` :h HiSync ` option :)

**Comment by azabiong** [comment]
Thanks for your update. Each window can have different highlighting patterns by default, and  you can use [Sync Mode](https://github.com/azabiong/vim-highlighter#sync-mode) and the configurable option ` :h HiSyncMode `.

**Comment by jqhr** [comment]
It works, Thanks you
